### PR TITLE
Improve support for nvidia proprietary drivers

### PR DESCRIPTION
**Pull request by zyga**
This patch hopefully improves nvidia support. It includes some upstream
work and configure-time options to bind mount nvidia binary drivers into
a location that all snaps look at.

Signed-off-by: Zygmunt Krynicki <me@zygoon.pl>

### CODE REVIEW

**Comment by timjp87** [comment]
I built my package from this branch, but after installing krita or ubuntu-calculator-app it still won't launch.
"libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Unrecognized OpenGL version
Unrecognized OpenGL version"

I rebooteded and tried adding the snappy.conf file that is shipped in /etc/ld.so.conf.d/ on Ubuntu but it still doesn't work.

**Comment by zyga** [comment]
Thanks for checking this. Can you tell me how you've installed your nvidia drivers please?

**Comment by timjp87** [comment]
https://github.com/ubuntu-core/snap-confine/pull/34/files#diff-b36836eb6c1896a2061fa1b22a97b268R37 
 
This could be the culprit. The directory on Arch doesn't include the version number. Arch ships the vendor neutral GL dispatch libraries in the glvnd package. See:  
https://www.archlinux.org/packages/extra/x86_64/libglvnd/
And uses /usr/lib/nvidia/ as directory. I don't know if snappy supports 32 Bit x86 apps on 64 Bit hosts, but that would probably need some special treatment for the driver too. The 32 Bit libs are in these directories:  
https://www.archlinux.org/packages/multilib/x86_64/lib32-libglvnd/

**Comment by zyga** [comment]
Ah, thank you.

This is just a short term hack. The long term solution is that all of this will be defined by snapd, at runtime. I'm working on a snapd feature where the layout of bind mounts that snap-confine applies is dynamic and can depend on connected interfaces *and* on the host distribution.

For now I will just hack-support those but later on they will live in a nice, arch-specific area of snapd that is easy to control and modify.

**Comment by chipaca** [comment]
@zyga ... and on the combination of host arch and snap arch, apparently! :-) (not that we support cross-arch ... _yet_) #patcheswelcome

**Comment by zyga** [comment]
@timjp87 hey, can you please check again. I've patched the branch from which this package is built from to include /usr/lib/nvidia.

**Comment by timjp87** [comment]
Strange I'm getting:  
cannot bind mount nvidia driver /usr/lib/nvidia/ -> /var/lib/snapd/lib/gl. errmsg: No such file or directory  
When launching krita. I can "ls -l /usr/lib/nvidia" and list all files including the libGL.so without problems.

**Comment by zyga** [comment]
Thanks, I'll check out what may be wrong there. Hmmm

**Comment by zyga** [comment]
Ah, I now see the problem. I wasn't doing the mounting correctly (there's a chroot there but I'm not using it correctly)

**Comment by zyga** [comment]
Try it now. It works for me :)

**Comment by timjp87** [comment]
usr/bin/krita: error while loading shared libraries: libGLX.so.0: cannot open shared object file: No such file or directory

this shared object is in /usr/lib on Arch.

**Comment by zyga** [comment]
Thanks, let me investigate that.

**Comment by zyga** [comment]
Hmm, I think I understand the problem. Now I'm looking for a solution. The problem is that on arch the actual nvidia libraries are in `/usr/lib/nvidia` but they depend on bits in `/usr/lib` that are not provided by neithre the core snap nor by various application snaps. On ubuntu /usr/lib/nvidia-*/ contains 

```
zyga@ubuntu:/usr/lib/nvidia-340$ ll
total 116348
drwxr-xr-x   6 root root     4096 Jun  7 06:51 ./
drwxr-xr-x 140 root root     4096 Jun  7 06:51 ../
-rw-r--r--   1 root root        0 Apr 14 11:42 alt_ld.so.conf
drwxr-xr-x   2 root root     4096 Jun  7 06:51 bin/
-rw-r--r--   1 root root       42 Apr 14 11:42 ld.so.conf
lrwxrwxrwx   1 root root       11 Apr 14 11:42 libEGL.so -> libEGL.so.1
lrwxrwxrwx   1 root root       16 Apr 14 11:42 libEGL.so.1 -> libEGL.so.340.96
-rw-r--r--   1 root root   987736 Nov  8  2015 libEGL.so.340.96
lrwxrwxrwx   1 root root       17 Apr 14 11:42 libGLESv1_CM.so -> libGLESv1_CM.so.1
lrwxrwxrwx   1 root root       22 Apr 14 11:42 libGLESv1_CM.so.1 -> libGLESv1_CM.so.340.96
-rw-r--r--   1 root root    48024 Nov  8  2015 libGLESv1_CM.so.340.96
lrwxrwxrwx   1 root root       14 Apr 14 11:42 libGLESv2.so -> libGLESv2.so.2
lrwxrwxrwx   1 root root       19 Apr 14 11:42 libGLESv2.so.2 -> libGLESv2.so.340.96
-rw-r--r--   1 root root    62160 Nov  8  2015 libGLESv2.so.340.96
lrwxrwxrwx   1 root root       10 Apr 14 11:42 libGL.so -> libGL.so.1
lrwxrwxrwx   1 root root       15 Apr 14 11:42 libGL.so.1 -> libGL.so.340.96
-rw-r--r--   1 root root  1267768 Nov  8  2015 libGL.so.340.96
lrwxrwxrwx   1 root root       15 Apr 14 11:42 libnvcuvid.so -> libnvcuvid.so.1
lrwxrwxrwx   1 root root       20 Apr 14 11:42 libnvcuvid.so.1 -> libnvcuvid.so.340.96
-rw-r--r--   1 root root  2712496 Nov  8  2015 libnvcuvid.so.340.96
lrwxrwxrwx   1 root root       18 Apr 14 11:42 libnvidia-cfg.so -> libnvidia-cfg.so.1
lrwxrwxrwx   1 root root       23 Apr 14 11:42 libnvidia-cfg.so.1 -> libnvidia-cfg.so.340.96
-rw-r--r--   1 root root   161800 Nov  8  2015 libnvidia-cfg.so.340.96
lrwxrwxrwx   1 root root       23 Apr 14 11:42 libnvidia-compiler.so -> libnvidia-compiler.so.1
lrwxrwxrwx   1 root root       28 Apr 14 11:42 libnvidia-compiler.so.1 -> libnvidia-compiler.so.340.96
-rw-r--r--   1 root root 25219152 Nov  8  2015 libnvidia-compiler.so.340.96
-rw-r--r--   1 root root 42508504 Nov  8  2015 libnvidia-eglcore.so.340.96
lrwxrwxrwx   1 root root       21 Apr 14 11:42 libnvidia-encode.so -> libnvidia-encode.so.1
lrwxrwxrwx   1 root root       26 Apr 14 11:42 libnvidia-encode.so.1 -> libnvidia-encode.so.340.96
-rw-r--r--   1 root root   160832 Nov  8  2015 libnvidia-encode.so.340.96
lrwxrwxrwx   1 root root       23 Jun  7 06:51 libnvidia-fbc.so.1 -> libnvidia-fbc.so.340.96
-rw-r--r--   1 root root    86088 Nov  8  2015 libnvidia-fbc.so.340.96
-rw-r--r--   1 root root 44003096 Nov  8  2015 libnvidia-glcore.so.340.96
-rw-r--r--   1 root root   481024 Nov  8  2015 libnvidia-glsi.so.340.96
lrwxrwxrwx   1 root root       18 Apr 14 11:42 libnvidia-ifr.so -> libnvidia-ifr.so.1
lrwxrwxrwx   1 root root       23 Apr 14 11:42 libnvidia-ifr.so.1 -> libnvidia-ifr.so.340.96
-rw-r--r--   1 root root   178376 Nov  8  2015 libnvidia-ifr.so.340.96
lrwxrwxrwx   1 root root       17 Apr 14 11:42 libnvidia-ml.so -> libnvidia-ml.so.1
lrwxrwxrwx   1 root root       22 Apr 14 11:42 libnvidia-ml.so.1 -> libnvidia-ml.so.340.96
-rw-r--r--   1 root root   880800 Nov  8  2015 libnvidia-ml.so.340.96
-rw-r--r--   1 root root    12696 Nov  8  2015 libnvidia-tls.so.340.96
lrwxrwxrwx   1 root root       23 Jun  7 06:51 libnvidia-wfb.so.1 -> libnvidia-wfb.so.340.96
-rw-r--r--   1 root root   295416 Dec 12  2012 libnvidia-wfb.so.340.96
drwxr-xr-x   2 root root     4096 Jun  7 06:51 tls/
drwxr-xr-x   2 root root     4096 Jun  7 06:51 vdpau/
drwxr-xr-x   2 root root     4096 Jun  7 06:51 xorg/
```

The critical fact is that those shared objects don't depend on things in `/usr/lib` that aren't either in the core snap or in various snaps we're trying this with.

```
zyga@ubuntu:/usr/lib/nvidia-340$ ldd libGL.so
	linux-vdso.so.1 =>  (0x00007ffc6f57e000)
	libnvidia-tls.so.340.96 => /usr/lib/nvidia-340/tls/libnvidia-tls.so.340.96 (0x00007f9a09fd6000)
	libnvidia-glcore.so.340.96 => /usr/lib/nvidia-340/libnvidia-glcore.so.340.96 (0x00007f9a073c2000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f9a07087000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f9a06e75000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9a06aac000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9a068a7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9a0659e000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f9a0637c000)
	/lib64/ld-linux-x86-64.so.2 (0x0000565410f11000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f9a06177000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f9a05f71000)
```

Now in arch the situation is slightly different:

```
razem 684
drwxr-xr-x   2 root root   4096 04-11 17:58 .
drwxr-xr-x 232 root root 118784 06-07 15:46 ..
lrwxrwxrwx   1 root root     21 04-11 17:58 libGLESv1_CM.so -> libGLESv1_CM.so.1.0.0
lrwxrwxrwx   1 root root     21 04-11 17:58 libGLESv1_CM.so.1 -> libGLESv1_CM.so.1.0.0
-rwxr-xr-x   1 root root  39200 04-11 17:58 libGLESv1_CM.so.1.0.0
lrwxrwxrwx   1 root root     18 04-11 17:58 libGLESv2.so -> libGLESv2.so.2.0.0
lrwxrwxrwx   1 root root     18 04-11 17:58 libGLESv2.so.2 -> libGLESv2.so.2.0.0
-rwxr-xr-x   1 root root  47392 04-11 17:58 libGLESv2.so.2.0.0
lrwxrwxrwx   1 root root     14 04-11 17:58 libGL.so -> libGL.so.1.0.0
lrwxrwxrwx   1 root root     14 04-11 17:58 libGL.so.1 -> libGL.so.1.0.0
-rwxr-xr-x   1 root root 481576 04-11 17:58 libGL.so.1.0.0
```

The problem with finding `libGLX.so` originates in the fact that it is in the part of arch (/usr/lib) that is overlapped with and hidden by the core snap. 

```
[zyga@arch nvidia]$ ldd libGL.so.1.0.0 
	linux-vdso.so.1 (0x00007ffe4e7ca000)
	libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007fe9c2090000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007fe9c1d4e000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x00007fe9c1b3c000)
	libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007fe9c1865000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fe9c1661000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fe9c1444000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fe9c10a2000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007fe9c0e79000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00005613bb56f000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007fe9c0c74000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007fe9c0a6e000)
```

To understand how libglnvd works it is useful to look at the diagram on https://github.com/NVIDIA/libglvnd 

(this post just states the problem, now let's look for a solution)

**Comment by zyga** [comment]
This should not work on all the drivers except the most recent 346 that use `libglvnd`.

**Comment by zyga** [comment]
Note that it requires yet-unpublished core snap to function. I'll write about how to use this in a moment.

**Comment by zyga** [comment]
Using this script this should be now good to test: https://gist.github.com/zyga/fc2919c7a96c66fef66cefdb9f4e89d9

**Comment by timjp87** [comment]
For some reason I still get:  
"usr/bin/krita: error while loading shared libraries: libGLX.so.0: cannot open shared object file: No such file or directory"  
I completely removed snapd-git and snap-confine-git. Pulled the latest commits of snapd-arch/master and of snap-confine-arch/nvidia-support. Ran "sudo snap install krita". Executed the script as root (ubuntu-core snap was downloaded and activated pretty quickly this time) and tried to launch krita from command line.

**Comment by zyga** [comment]
@timjp87 this is expected if you use the latest version of the nvidia driver. If you have the older driver (340) it works okay. I'm working on getting more drivers supported.

**Comment by zyga** [comment]
I'll merge this for now. We should iterate upstream and switch to an official release.

**Pull request merged**
